"""
GSIS GLOBAL TRADING CONFIGURATION
Version: 1.0
"""

# Trading Style
TRADING_MODE = "SWING"

# Signal Requirements
MIN_CONFIDENCE = 0.75
MIN_SIGNAL_GRADE = "A"
MIN_FUSION_SCORE = 6

# Strategy Filters
REQUIRE_REGIME_CONFIRMATION = True
REQUIRE_VOLUME_CONFIRMATION = True
REQUIRE_ORDERFLOW_CONFIRMATION = True
REQUIRE_QUALITY_GATE = True

# Trading Permissions
ALLOW_LONG = True
ALLOW_SHORT = True

# Time Filters
ENABLE_SESSION_FILTER = True
ENABLE_NEWS_FILTER = True

# Trade Frequency
MAX_TRADES_PER_DAY = 5
MAX_SIMULTANEOUS_TRADES = 3

# Scanner
SCAN_INTERVAL_SECONDS = 60
